"""creat users table2

Revision ID: 1048999e6248
Revises: d2ede06bbc99
Create Date: 2022-11-10 08:18:57.892898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1048999e6248'
down_revision = 'd2ede06bbc99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
